import os
from datetime import datetime


class DocsGenerator:
    def summarise_file(self, filename, content):
        file_ext = os.path.splitext(filename)[1]

        doc_content = f"""# {filename}

**Generated on:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**File type:** {file_ext}
**Lines of code:** {len(content.splitlines())}

## Summary

TODO: AI-generated summary of the file's purpose and functionality.

## Key Components

TODO: List of main classes, functions, or modules in this file.

## Dependencies

TODO: External dependencies and imports used in this file.

## Usage Examples

TODO: Examples of how this code is used or called.

---
*This documentation was auto-generated by IntelliDocs*
"""

        return doc_content
